### ISSUE TITLE
Three cell example does not run

### ISSUE THREAD

**Issue by RokasSt** [OpenSourceBrain/VERTEXShowcase#11]
Hi Richard,

May you look at this script;

https://github.com/OpenSourceBrain/VERTEXShowcase/blob/master/VERTEX/Adex2pop_1comp_test4.m

 apparently the network is initialized but then I get the error in MATLAB: 

Attempt to reference field of non-structure array.

Error in PointNeuronModel.sumSynapticCurrents (line 32)
          I_syn = I_syn + SM{iSyn}.I_syn();

Error in ......

I reviewed the script so many times and compared to other examples but I could not find what might be wrong. Maybe my eye is not catching something.

Thanks!
Regards, Rokas 

@richardtomsett

**Comment by richardtomsett** [comment]
Ah this was a bug in the PointNeuronModel class that causes this error if there are no synapses. I've fixed this in the main VERTEX branch - let me know if you still get the error after downloading the latest version! @RokasSt

**Comment by RokasSt** [comment]
Yes, now it is fine, thanks!

@richardtomsett
