### ISSUE TITLE
rotate3DCoordinates.m and rotationAngleMat

### ISSUE THREAD

**Issue by RokasSt** [OpenSourceBrain/VERTEXShowcase#14]
Hi Richard,
I wanted to ask you where you are using the rotate3DCoordinates function and rotationAngleMat array in the VERTEX scripts because I cannot find them so far in the scripts.

Thank you

@richardtomsett

**Comment by richardtomsett** [comment]
Howdy,
VERTEX only bothers to calculate the rotations if LFPs are being calculated (it makes no difference to the connectivity) so rotate3DCoordinates() and rotationAngleMat are only used in vertex_LFP/calculateLineSourceModifiers.m
Looking back this doesn't make so much sense but it seemed to at the time...
@RokasSt

**Comment by RokasSt** [comment]
Understood, thanks!

@richardtomsett
