### ISSUE TITLE
Unit handling

### ISSUE THREAD

**Issue by RokasSt** [OpenSourceBrain/VERTEXShowcase#16]
Hi Richard,

I hope you could find some time to respond to this.

Is it true that VERTEX does not handle SI units without complains? I am testing some import of cell models from LEMS to VERTEX, and NeuroML export utils convert everything to SI units. When I give these parameter values  in SI units VERTEX runs simulation only if time step and simulation time is in ms. However, the potential is actually not simulated - v_m array is constant staying at the initial value.

Also,  if I give time in sec, VERTEX still assumes that this small value (let's say 10E-5) is in ms, when in LEMS it is actually in sec, and VERTEX complains about incompatibility of maxRec, timeStep etc, all issues we discussed and have NOT been problematic when they were handled in ms.

Thanks!
Best Regards,
Rokas
@richardtomsett

**Comment by richardtomsett** [comment]
Hi @RokasSt ,
VERTEX doesn't do any unit checking at all, it just assumes your times, currents, conductances, voltages, resistances etc. are in particular units. These I should list somewhere! But for now I'll do it here:

| Physical quantity | Unit used | Example |
| --- | --- | --- |
| ￼Electric potential | mV | membrane potential _v_ |
| Conductance | nS | synaptic conductance _g<sub>syn</sub>_ |
| Current | pA | synaptic current _I<sub>syn</sub>_ |
| Specific resistance | Ω·cm<sup>2</sup> | Specific membrane resistance _R<sub>M</sub>_ |
| Specific capacitance | μF · cm<sup>−2</sup> | Specific membrane capacitance _C<sub>M</sub>_ |
| Longitudinal resistance | Ω·cm | Intracellular axial resistance _R<sub>A</sub>_ |
| Conductivity | S·m<sup>−1</sup> | Extracellular conductivity _σ_ |
| Time | ms | Synaptic time constant _τ<sub>syn</sub>_ |
| Length | μm | Model width _X_ |

So if you give a time of 10E-5, it will be interpreted as 10E-5 ms i.e. 10E-8 s. I'm afraid I never implemented a proper units/unit checking system, I just set up the relevant equations to assume the above units... does that help?

**Comment by RokasSt** [comment]
Hi, Richard

Thanks for your response, so I will then enable conversion of SI units to the units the VERTEX assumes

Best Regards,
Rokas
@richardtomsett
