### ISSUE TITLE
Unit mismatch 

### ISSUE THREAD

**Issue by RokasSt** [OpenSourceBrain/VERTEXShowcase#7]
In the tutorial 1  http://vertexsimulator.org/tutorial-1/ it is given that C is a specific membrane capacitance in microFarads per square centimetre. Assuming this, your code in the VERTEX script calculatePassiveProperties.m calculates membrane capacitance as C_m =NP(iGroup).C .\* pi .\* l .\* d .\* 10^6 with the comment that this is now in nanoFarads;also l and d are converted to cm by getDimensionsInCenti...... function. However,  when I did simple unit analysis I found that it is actually Farads, not nanoFarads:
(microFarads/ cm ^2)\* cm \* cm *10^6= micro *10^6 Farads = Farads.

g_l seems to be okay, in contrast:
 R_M = NP(iGroup).R_M ./ (pi .\* l .\* d); % in Ohms
    NP(iGroup).g_l = 10^9 ./ R_M; % in nanoSiemens, 

where R_M= ohms*cm2, according to tutorial1.

Would be helpful if you can look at this, as LEMS carries about units, thanks!

@richardtomsett

**Comment by richardtomsett** [comment]
You're quite right the comment is incorrect! But it should read picoFarads, not nanoFarads or Farads. To get Farads, you would have to divide by 10^6, not multiply by 10^6 (the number of Farads must be smaller than the number of picoFarads). I'll edit the comment - sorry for the confusion!

This stuff should probably all be in NeuronModel class methods really, but isn't for bad historical reasons...

**Comment by RokasSt** [comment]
Thanks for the response, so the comment should be picoFarads
